# DO NOT EDIT THIS FILE!
#
# Python module CrudApp generated by omniidl

import omniORB
omniORB.updateModule("CrudApp")

# ** 1. Stub files contributing to this module
import crudbanco_idl

# ** 2. Sub-modules

# ** 3. End
